### PR TITLE
add live ops as co-owners

### PR DESCRIPTION
**Pull request by LeadTimeNull**
Create owners alias for the live ops team; list all GH usernames, and comments with full names.

### CODE REVIEW

**Review by petemounce — APPROVED** [review]

**Comment by jared-improbable** [comment]
What needs to happen to get this merged?

**Comment by petemounce** [comment]
I need to remember that this was blocked (sorry!), inspect the CI failure (already done; not related to this change), and exercise my admin rights to merge past the branch protection.

Apologies for viscosity.

**Pull request merged**
