### PR TITLE
Update p4python version to latest

### PR DESCRIPTION
**Pull request by improbable-mattchurch**

### CODE REVIEW

**Comment by improbable-mattchurch** [comment]
I believe the Travis CI failure is related to python 3.9 being incompatible with p4python.

**Comment by LeadTimeNull** [comment]
Do we need to upgrade to python 3.9, or can we keep p4python using its own virtual environment?

**Comment by improbable-mattchurch** [comment]
I believe we need to use another version of python for our macos test agent

**Comment by LeadTimeNull** [comment]
The error is almost certainly unrelated to your changes. This issue was observed in the past, changing docs files.
@jared-improbable discussed it with @petemounce and IIRC it was decided that we don't wish to go through the trouble of supporting the MacOS pipeline. 
@petemounce is out sick today, perhaps @DoomGerbil will be able to weigh in?

edit: @DoomGerbil , do you have any objection to @improbable-mattchurch having his merge pushed through on this?

**Comment by DoomGerbil** [comment]
> IIRC it was decided that we don't wish to go through the trouble of supporting the MacOS pipeline.

If this is the case, then we should switch off the mac job so it doesn't keep failing. That said, from a quick glance at the logs, I think @improbable-mattchurch is right about the 3.9.0 version being the problem. [p4python](https://www.perforce.com/perforce/r15.1/user/p4pythonnotes.txt) only actually claims compatibility with Python 2.6, 2.7, 3.3, and 3.4, and we're using none of those.

So basically yep, I can override the red tests and then disable the mac pipeline on `master` post-facto.

**Review by DoomGerbil — APPROVED** [review]
LGTM

**Comment by DoomGerbil** [comment]
Ah ha, then again, https://github.com/improbable-eng/perforce-buildkite-plugin/pull/213 exists. I'll see if this fixes things first, and if it does, I'll do that.

Otherwise, I'll switch off osx builds for the meantime.

**Comment by DoomGerbil** [comment]
https://github.com/improbable-eng/perforce-buildkite-plugin/pull/222 is now open to disable the osx build for now.

**Pull request merged**
